USE HEALTHCARE;
SELECT * FROM PATIENT_INFO;

 -- SQL QUERIES
 -- 1. TOTAL NUMBER OF PATIENTS
 SELECT COUNT(*) FROM patient_info;
 
 -- 2. UNIQUE DISEASE COUNT
 SELECT COUNT(distinct DISEASE_NAME) AS COUNT_DISEASES FROM PATIENT_INFO;
 
 -- 3. NUMBER OF PATIENT DISTRIBUTION BY GENDER
 SELECT GENDER, COUNT(*) AS COUNT_GENDER 
 FROM PATIENT_INFO
 GROUP BY 1
 ORDER BY 2 DESC;
 
 -- 4. LIST ALL UNIQUE DISEASES
 SELECT DISTINCT DISEASE_NAME FROM PATIENT_INFO;
 
 -- 5. AVERAGE PATIENT AGE
 SELECT avg(AGE) AS AVG_AGE  FROM patient_info;
 
 -- 6. TOTAL TREATMENT COST
 SELECT SUM(TREATMENT_COST_INR) AS TOTAL_TREATMENT_COST FROM PATIENT_INFO;
 
-- 7. TOP 5 MOST COMMAN DISEASES
SELECT DISEASE_NAME, COUNT(*) AS CASES FROM patient_info
GROUP BY disease_name
ORDER BY CASES DESC
LIMIT 5;

SELECT * FROM patient_info ;

-- 8. PATIENT COUNT BY STATE
SELECT STATE, COUNT(*) AS TOTAL_PATIENTS FROM patient_info
GROUP BY STATE
ORDER BY 2 DESC; 


-- 9. AVERAGE TREATMENT COST PER DISEASE
SELECT  DISEASE_NAME, ROUND(AVG(TREATMENT_COST_INR),2) AS AVG_COST_PER_DISEASE
FROM PATIENT_INFO
GROUP BY 1
ORDER BY 2 DESC;

-- 10. CALCULATE THE PATIENTS WHOSE AGE IS ABOVE 60 YEARS
SELECT PATIENT_ID, AGE, GENDER, DISEASE_NAME FROM PATIENT_INFO
WHERE AGE > 60 ;

-- 11. CALCULATE THE TOTAL PATIENTS PER CITY 
select CITY, COUNT(*) AS TOTAL_PATIENTS
FROM patient_info
GROUP BY CITY
ORDER BY TOTAL_PATIENTS DESC;

-- 10. CALCULATE MAXIMUM AND MINIMUM TREATMENT COST
SELECT MAX(TREATMENT_COST_INR) AS MAX_COST, 
		min(TREATMENT_COST_INR) AS MIN_COST
FROM PATIENT_INFO;

-- 11. CALCULATE DISEASE WITH HIGHEST TREATMENT COST
SELECT DISEASE_NAME, SUM(TREATMENT_COST_INR) AS 'TOTAL_COST' FROM patient_info
GROUP BY DISEASE_NAME
ORDER BY 2 DESC 
LIMIT 1;

-- 12. MORTALITY RATE BY DISEASE
SELECT DISEASE_NAME, COUNT(*) AS TOTAL_CASES,
SUM(DEATH_FLAG) AS DEATH,
(SUM(DEATH_FLAG) * 100 / COUNT(*) ) AS MORTALITY_RATE 
FROM PATIENT_INFO
GROUP BY DISEASE_NAME;

SELECT * FROM PATIENT_INFO;

-- 13. AVERAGE HOSPITAL STAY BY SEVERITY
SELECT SEVERITY, AVG(DAYS_HOSPITALIZED) AS AVG_STAYS
FROM PATIENT_INFO
GROUP BY SEVERITY; 

-- 14. MONTHLY PATIENT TREND
SELECT YEAR, MONTH, COUNT(*) AS TOTAL_CASES
FROM PATIENT_INFO
GROUP BY 1,2
ORDER BY 1,2;

-- 15. URBAN vs RURAL COMPARISON
SELECT URBAN_RURAL,
ROUND(AVG(TREATMENT_COST_INR),2) AS AVG_COST,
ROUND(AVG(DAYS_HOSPITALIZED),1) AS AVG_STAYS
FROM patient_info
GROUP BY 1;

-- 16. INSURANCE vs TREATMENT COST
SELECT INSURANCE_STATUS,
	ROUND(AVG(TREATMENT_COST_INR),2) AS AVG_COST
FROM PATIENT_INFO
GROUP BY 1
ORDER BY 2 ;

-- 17. TOP 5 DISEASES WITH HIGHEST RECOVERY TIME
SELECT DISEASE_NAME, ROUND(AVG(RECOVERY_DAYS),0) AS AVG_RECOVERY_DAYS
FROM PATIENT_INFO
GROUP BY DISEASE_NAME
ORDER BY 2 DESC;

-- 18. SMOKING IMPACT ON SEVERITY
SELECT SMOKING_STATUS, SEVERITY, COUNT(*) AS PATIENT
FROM patient_info
GROUP BY 1,2;

-- 19. COUNT OF PATIENTS BY HOSPITAL TYPE
SELECT HOSPITAL_TYPE, COUNT(*) AS TOTAL_PATIENTS
FROM PATIENT_INFO
GROUP BY 1;

-- 20. RANK DISEASES BY TREATMENT COST (WINDOWS FUNCTION)
SELECT DISEASE_NAME,
ROUND(AVG(TREATMENT_COST_INR),2) AS AVG_COST,
RANK() OVER (ORDER BY AVG(TREATMENT_COST_INR) DESC) AS COST_RANK
FROM PATIENT_INFO
GROUP BY 1;

-- 21. TOP 3 COSTLY DISEASES IN EACH REGION
SELECT * FROM
(
SELECT REGION, DISEASE_NAME, ROUND(AVG(TREATMENT_COST_INR),2) AS AVG_COST,
RANK() OVER (PARTITION BY REGION ORDER BY AVG(TREATMENT_COST_INR) DESC) AS RNK
FROM PATIENT_INFO
GROUP BY 1,2
) AS T1
WHERE RNK <= 3;


-- 22. RUNNING TOTAL OF PATIENTS OVER TIME
SELECT year, month,
       COUNT(*) AS MONTHLY_CASES,
       SUM(COUNT(*)) OVER (ORDER BY year, month) AS running_total
FROM patient_info
GROUP BY YEAR, MONTH ;


-- 23. PATIENT WITH ABOVE AVERAGE TREATMENT COST
SELECT * FROM PATIENT_INFO
WHERE TREATMENT_COST_INR > 
(SELECT AVG(TREATMENT_COST_INR) FROM PATIENT_INFO );

-- 24. CASE STATEMENT FOR RISK CATEGORY
SELECT PATIENT_ID, SEVERITY,
	CASE
		WHEN SEVERITY = 'HIGH' THEN 'CRITICAL'
        WHEN SEVERITY = 'LOW' THEN 'MODERATE'
        ELSE 'LOW_RISK'
	END AS RISK_CATEGORY
FROM PATIENT_INFO;

-- 25. DEATH RATE BY COMORBIDITY
SELECT COMORBIDITY, COUNT(*) AS TOTAL,
SUM(DEATH_FLAG) AS DEATHS,
(SUM(DEATH_FLAG) * 100 / COUNT(*) ) AS DEATH_RATE
FROM PATIENT_INFO
GROUP BY COMORBIDITY;
